version: "3.3"

services:
    backend:
        build: 
            context: "./backend"
            dockerfile: "./dockerfile"
        command: /start-reload.sh
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`localhost`) && PathPrefix(`/docs`, `/api`, `/redoc`)"
        volumes:
            - ./backend/app:/app
    traefik:
        image: "traefik:v2.2.0"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"