"""Todo model

Revision ID: 982de30c4868
Revises: 1acd43bb4b7b
Create Date: 2020-04-16 19:53:53.600445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982de30c4868'
down_revision = '1acd43bb4b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_description'), 'todo', ['description'], unique=False)
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_index(op.f('ix_todo_description'), table_name='todo')
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
