"""Todo model - Add completed field

Revision ID: c65b8da25c1e
Revises: 982de30c4868
Create Date: 2020-04-16 20:01:16.744253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65b8da25c1e'
down_revision = '982de30c4868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_todo_completed'), 'todo', ['completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_completed'), table_name='todo')
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
